name: gpdf
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest-small
    steps:
      - uses: actions/checkout@v3
      - run: pwd && which xetex 
      - uses: actions/upload-artifact@v3
        with:
          path: **
